### PR TITLE
Multi gpu support

### PR DESCRIPTION
**Pull request by fepitre**
Add Multi GPUs support.

Major rework of all the PCI devices handling in order to correctly manage GPUs with their related consumers and bridges. It allows to pass necessary devices to VFIO when GPUs are selected.

Few fixes and some fixed issues:
Closes: https://github.com/golemfactory/golem-gpu-live/issues/28
Closes https://github.com/golemfactory/golem-gpu-live/issues/29
Closes https://github.com/golemfactory/golem-gpu-live/issues/30

### CODE REVIEW

**Review by stan7123 — COMMENTED** [review]
When GPU selection window is presented, user should select the GPU.
The problem is that many users can be unaware that "the space" key should be used.
Pushing the Enter key is active and when it's pressed it confirms the step. The wizard goes further and there's an error because no GPU was selected. All the process must be repeated (entering wallet address etc.)
My suggestion is to make the Enter key inactive somehow (I'm not sure what is possible):
- making Enter key active again when at least one GPU is selected,
- changing focus to the list, not the OK button on the bottom,
- making OK button inactive until the GPU is selected,
or other methods which will prevent user from going further without selecting GPU.

**Comment by fepitre** [comment]
Here is now how the GPU selection is:

Screenshot 2024-08-03 at 11-36-47 snapshot (JPEG Image 1920 × 1080 pixels) — Scaled (89_)

On any mistake or empty selection you get this warning message that got you back after to GPU selection:

Screenshot 2024-08-03 at 11-36-42 snapshot (JPEG Image 1920 × 1080 pixels) — Scaled (89_)

Once you selected GPUs you need to confirm, else it gets you back to GPU selection:

Screenshot 2024-08-03 at 11-36-32 snapshot (JPEG Image 1920 × 1080 pixels) — Scaled (89_)

**Comment by cryptobench** [comment]
@fepitre 

Heya! I'm currently preparing our reputation system to handle multiple GPU's instead of just a single.

I am looking to understand the structure of the proposals that the providers are sending out on the network. I have the following questions:

```
    'golem.!exp.gap-35.v1.inf.gpu.cuda.driver.version': '535.183.01',
    'golem.!exp.gap-35.v1.inf.gpu.cuda.version': '12.2',
    'golem.!exp.gap-35.v1.inf.gpu.d0.clock.graphics.mhz': 3150,
    'golem.!exp.gap-35.v1.inf.gpu.d0.clock.memory.mhz': 10501,
    'golem.!exp.gap-35.v1.inf.gpu.d0.clock.sm.mhz': 3150,
    'golem.!exp.gap-35.v1.inf.gpu.d0.clock.video.mhz': 2415,
    'golem.!exp.gap-35.v1.inf.gpu.d0.cuda.caps': '8.9',
    'golem.!exp.gap-35.v1.inf.gpu.d0.cuda.cores': 16384,
    'golem.!exp.gap-35.v1.inf.gpu.d0.cuda.enabled': true,
    'golem.!exp.gap-35.v1.inf.gpu.d0.memory.bandwidth.gib': 1008,
    'golem.!exp.gap-35.v1.inf.gpu.d0.memory.total.gib': 23.98828125,
    'golem.!exp.gap-35.v1.inf.gpu.d0.model': 'NVIDIA GeForce RTX 4090',
    'golem.!exp.gap-35.v1.inf.gpu.d0.quantity': 4,
```


> So is it correctly understood that ->
> 
> 1) cuda version + driver will remain the same no matter how many GPU's the provider has? It's not labelled as .d0, so thats why im assuming that
> 
> 2) For every GPU available, I can expect that:
> 1 GPU = d0,
> 2 GPU's = d0 + d1,
> 3 GPUS = d0 +d1 +d2
> and so on? 
> 
> 
> Oh wait I just noticed that there's a quantity. Does this mean there's 4 4090's in the system above? 
> 
> Is it possible to mix for example 4090 + A100's in the same system? How would that look like?



Would you be able to answer that question?

**Comment by marmarek** [comment]
> 1. cuda version + driver will remain the same no matter how many GPU's the provider has? It's not labelled as .d0, so thats why im assuming that

Yes

> 2\. For every GPU available, I can expect that:
>         1 GPU = d0,
>         2 GPU's = d0 + d1,
>         3 GPUS = d0 +d1 +d2
>         and so on?
> 
> 
> Oh wait I just noticed that there's a quantity. Does this mean there's 4 4090's in the system above?

Same GPUs are combined, with quantity > 1. If they are different, they will be under new dN number. So, 2x4090 + 2x3080 will have d0+d1, but 4x4090 will have only d0.

**Comment by cryptobench** [comment]
> > 1. cuda version + driver will remain the same no matter how many GPU's the provider has? It's not labelled as .d0, so thats why im assuming that
> 
> Yes
> 
> > 2. For every GPU available, I can expect that:
> > 1 GPU = d0,
> > 2 GPU's = d0 + d1,
> > 3 GPUS = d0 +d1 +d2
> > and so on?
> > Oh wait I just noticed that there's a quantity. Does this mean there's 4 4090's in the system above?
> 
> Same GPUs are combined, with quantity > 1. If they are different, they will be under new dN number. So, 2x4090 + 2x3080 will have d0+d1, but 4x4090 will have only d0.

Thank you very much for the clarification!

**Comment by cryptobench** [comment]
@marmarek Does the multi-GPU support enable requestors to rent a single GPU from a provider who has multiple GPU's?

Say for example the provider has 8x A100, can the requestor rent 3 of them and leave the remaining 5?

**Comment by marmarek** [comment]
I don't think so, yagna doesn't seems to support such case. It's always all of those connected to the provider at once.
We have discussed whether it should be connected each GPU to separate provider (allowing to rent each individually) or all at once, and the decision was to do with the latter option.

**Comment by cryptobench** [comment]
> I don't think so, yagna doesn't seems to support such case. It's always all of those connected to the provider at once. We have discussed whether it should be connected each GPU to separate provider (allowing to rent each individually) or all at once, and the decision was to do with the latter option.

No that's right Yagna doesn't support it by default but I was wondering if anything new had been made. 

Thanks for the reply as always!

**Pull request merged**
