### PR TITLE
added grub config for kernel updates

### PR DESCRIPTION
**Pull request by prekucki**

### CODE REVIEW

**Comment by marmarek** [comment]
To preserve the "NO AUTOSTART" boot entry after regenerating config, I'd put it into `/boot/grub/custom.cfg` (boot partition is populated in https://github.com/golemfactory/golem-gpu-live/blob/devel/create-live-image.sh#L80 and the current boot entry is in https://github.com/golemfactory/golem-gpu-live/blob/devel/live/grub.cfg)

**Comment by prekucki** [comment]
@EvilSeeQu-sys i'm waiting for test.

**Comment by EvilSeeQu-sys** [comment]
Problem with boot look like solved but provider still fails to run after reboot :

golem@golem-provider:~/.local/share/yagna$ golemsp status
[2024-03-28T09:15:28Z ERROR golemsp] Unable to determine payment network used by the Yagna Provider.

[logs.zip](https://github.com/golemfactory/golem-gpu-live/files/14787016/logs.zip)

**Comment by stan7123** [comment]
@prekucki Is there any progress on this? Do you consider this finished?

**Pull request merged**
